version: '3' # composeファイルのバーション指定
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: CleanArchitecture
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db-data:/var/lib/mysql
      - ./api/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  back: # service名
    build: ./api # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化
    environment:
      MYAPP_DATABASE_HOST: db
    #command: "go run server.go"
    volumes:
      # - ./api:/api # マウントディレクトリ指定
      - ./:/go/src
    ports:
      - "8080:8080"
    links:
      - db

volumes:
  db-data:
